services:
  - type: web
    name: facetrack
    runtime: node
    plan: free
    buildCommand: npm install --include=prod && cd client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/stats
    autoDeploy: true
